[package]
name = "make-public-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
# syn = { version = "2.0.39", features = ["extra-traits"] }
syn = { version = "2.0.39", features = ["full", "extra-traits"] }
quote = "1.0.33"

[lib]
proc-macro = true
